var arr=[
['Maharashtra',['Pune','Achalapur','Akola ','Badlapur','Baramati','Ambernath','Mumbai']],
['Delhi',['Delhi city 1','New Delhi 2','Shadhara']],
['Gujarat',['Bhuj',
        	'Champaner',
        	'Chotta Udepur',
        	'Dabhoi',
        	'Danta',
        	'Dharampur',
        	'Dhoraji',
        	'Gondal',
        	'Halvad',
        	'Idar',
        	'Lakhpat',
        	'Mandvi',
        	'Morbi',
        	'Patan',
        	'Porbandar',
        	'Siddhapur',
        	'Vansada',
        	'Wadhvan',
        	'Wankaner',
        	'Zinzuwada']]
];